name: CI/CD - Test and Deploy to ECR

on:
  push:
    branches:
      - dev

jobs:
  run-tests:
    # ... [keep your existing test job unchanged] ...

  build-and-push:
    name: Build and Push Docker Image to Two ECR Repositories
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FASTAPI_REPO: fastapi-swagger
          CLOUDWATCH_REPO: cloudwatch
          SHORT_SHA: ${{ github.sha }}  # Keep full SHA for traceability
        run: |
          # Build with both repository tags
          docker build -t $ECR_REGISTRY/$FASTAPI_REPO:$SHORT_SHA \
                       -t $ECR_REGISTRY/$FASTAPI_REPO:latest \
                       -t $ECR_REGISTRY/$CLOUDWATCH_REPO:$SHORT_SHA \
                       -t $ECR_REGISTRY/$CLOUDWATCH_REPO:latest .
          
          # Push to both repositories with both tags
          docker push $ECR_REGISTRY/$FASTAPI_REPO:$SHORT_SHA
          docker push $ECR_REGISTRY/$FASTAPI_REPO:latest
          docker push $ECR_REGISTRY/$CLOUDWATCH_REPO:$SHORT_SHA
          docker push $ECR_REGISTRY/$CLOUDWATCH_REPO:latest
