name: CI/CD - Build and Push to ECR

on:
  push:
    branches:
      - dev  # Trigger only on pushes to 'dev' branch

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pytest
          
      - name: Run Tests
        run: |
          mkdir -p test-results
          pytest tests/ \
            --junitxml=test-results/results.xml \
            --cov=src \
            --cov-report=xml:coverage.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            test-results/results.xml
            coverage.xml

  build-and-push:
    name: Build and Push to ECR
    needs: run-tests  # Depends on test job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Update your region if needed

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPO_1: "fastapi-swagger"  # First ECR repo
          REPO_2: "cloudwatch"       # Second ECR repo
          TAG: ${{ github.sha }}     # Commit SHA as primary tag
        run: |
          # Build with multiple tags (SHA + latest for both repos)
          docker build \
            -t $ECR_REGISTRY/$REPO_1:$TAG \
            -t $ECR_REGISTRY/$REPO_1:latest \
            -t $ECR_REGISTRY/$REPO_2:$TAG \
            -t $ECR_REGISTRY/$REPO_2:latest \
            .

      - name: Push to ECR
        run: |
          # Push all tags to both repositories
          docker push $ECR_REGISTRY/$REPO_1:$TAG
          docker push $ECR_REGISTRY/$REPO_1:latest
          docker push $ECR_REGISTRY/$REPO_2:$TAG
          docker push $ECR_REGISTRY/$REPO_2:latest
